### ISSUE TITLE
Mobile Detect fails

### ISSUE THREAD

**Issue by keiserjb** [backdrop-contrib/back_to_top#11]
When I install this module on my site and turn it on I get the following message and the site completely breaks.  

Fatal error: Cannot declare class Mobile_Detect, because the name is already in use in /app/modules/mobile_detect/library/Mobile_Detect.php on line 28

**Comment by laryn** [comment]
@BWPanda If you need the mobile detect library here, you could just make a dependency on 
https://github.com/backdrop-contrib/mobile_detect

OR a soft dependency where it checks if mobile_detect is installed and uses it if so, otherwise it uses the copy you've bundled...

**Comment by ghost** [comment]
Good idea @laryn. I'm sure I must have thought about this myself at the time, as I posted https://github.com/backdrop-contrib/mobile_detect/issues/2 a few weeks after adding this code here. Maybe I was waiting on that feature to go in first... I can't recall.

In any case, here's a PR. Please test: https://github.com/backdrop-contrib/back_to_top/pull/12

**Comment by laryn** [comment]
@keiserjb Are you able to test?
Thanks @BWPanda!

**Comment by keiserjb** [comment]
Sure, I've just got to figure out how.

**Comment by keiserjb** [comment]
It works for me now, and that's pretty cool.

**Comment by ghost** [comment]
Thanks @keiserjb. Committed. This change will be in the next release.
