### ISSUE TITLE
Fade out more when scrolling down

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/back_to_top#3]
For better UX, can we make the button/text fade out more when the user scrolls down the page? Here's an example of this: https://codyhouse.co/demo/back-to-top/index.html (there's also a link there to the original article with code if that helps).

**Comment by klonos** [comment]
Hey @BWPanda! We don't get to see you very often in the queues. Hope everything is OK.

Can you please elaborate a bit more on how this would improve the UX. I'm interested in UX improvements in general.

**Comment by ghost** [comment]
Hi @klonos! Yeah, going well. I don't contribute much (with PR's, etc.) unfortunately as I'm busy with work, but I'm currently re-building packweb.com.au in Backdrop (where I'm using this module actually) and when that launches I'll be advertising Backdrop services, so hope to be doing more with it in future.

As for this module, I just thought it'd enhance the UX as it's not this opaque box/button possibly sitting on top of content (especially on smaller screens) - being slightly faded out would mean it's still there and usable, but not as obvious and in-your-face. Also, a checkbox in the settings to control this behaviour would be good for those that don't want it fading out again.

**Comment by klonos** [comment]
Thanx for taking the time to explain @BWPanda. It makes more sense now. As for lack of time, no need to say anything further. Real Life™ issue queue comes first 😉

**Comment by ghost** [comment]
A similar feature is built into the new 1.x-2.x version, which can be further customised with custom CSS.
