### ISSUE TITLE
Back to Top creates a ghost role (older release downloaded by default)

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/back_to_top#9]
As [reported in the Forum](https://forum.backdropcms.org/comment/1311#comment-1311):

> Hi, i have found the problem, it happened again with the new page fresh install, the problem is the "Back to Top" module.
> Just after install it, the permission page gets damaged and creates an invisible role
> I found that it creates a file in /files/config_/active  named "user.role..json", just delete this file and problem solved.

I've experienced the same thing but hadn't tracked it down to this module.

**Comment by laryn** [comment]
I think this is because:

1. The project installer is pulling an old version (1.x-1.1.2) instead of the latest version (1.x-2.0.2).
2. This code perhaps (in the outdated version that gets installed): https://github.com/backdrop-contrib/back_to_top/blob/1.x-1.x/back_to_top.module#L188-L199

**Comment by klonos** [comment]
Hmmm 🤔 ...yeah, 1.1.2 is somehow marked as the latest release [on GitHub](https://github.com/backdrop-contrib/back_to_top/releases):

<img width="624" alt="Screen Shot 2019-10-03 at 5 05 57 am" src="https://user-images.githubusercontent.com/2423362/66074033-a7d5a980-e59b-11e9-9874-169a6e0863c3.png">

**Comment by klonos** [comment]
...I've made the older releases a pre-release on GitHub + unpublished them from b.org (all besides 1.x-2.0.1). It should be fixed now:

<img width="606" alt="Screen Shot 2019-10-03 at 5 14 40 am" src="https://user-images.githubusercontent.com/2423362/66074748-444c7b80-e59d-11e9-8eb3-b726a8ce4988.png">
